# Generated by Django 4.0.3 on 2022-03-25 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('rid', models.CharField(max_length=75, verbose_name='Resource ID')),
                ('rtype', models.CharField(choices=[('EC2', 'EC2')], max_length=10, verbose_name='Resource Type')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
            ],
        ),
    ]
