# Generated by Django 4.0.3 on 2022-03-25 23:09

from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwsAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('key_id', models.CharField(max_length=128)),
                ('key_secret', encrypted_model_fields.fields.EncryptedCharField()),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
            ],
        ),
        migrations.AddField(
            model_name='resource',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resources.awsaccount'),
        ),
    ]
