# Generated by Django 4.0.3 on 2022-03-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_awsaccount_resource_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='endpoint',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='region',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
