# Generated by Django 4.0.3 on 2022-04-01 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0008_alter_region_name_alter_region_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostedZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('base_domain', models.CharField(max_length=255)),
                ('zone_id', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.awsaccount')),
            ],
        ),
        migrations.AddField(
            model_name='resource',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resources.hostedzone'),
        ),
    ]
