# Generated by Django 4.0.3 on 2022-04-01 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0009_hostedzone_resource_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='zone_update',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private')], default='PUBLIC', max_length=10),
            preserve_default=False,
        ),
    ]
