# Generated by Django 4.0.3 on 2022-04-04 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0011_resource_last_zone_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_ts', models.DateTimeField(db_index=True)),
                ('event_type', models.CharField(choices=[('ON', 'On'), ('OFF', 'Off')], max_length=3)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.resource')),
            ],
            options={
                'ordering': ('event_ts',),
            },
        ),
    ]
