# Generated by Django 4.0.3 on 2022-04-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0013_resource_disable_power_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='powerschedule',
            name='last_executed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
