# Generated by Django 4.0.3 on 2022-04-25 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0015_alter_permission_actions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostedzone',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.awsaccount'),
        ),
        migrations.AlterField(
            model_name='hostedzone',
            name='zone_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
